### ISSUE TITLE
error: command list

### ISSUE THREAD

**Issue by brunooomelo** [brunooomelo/gitprofiles#4]
``` sh
  gitprofile list
```
when `.gitprofile.yml` is empty.

```sh 
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at buildResponse (/usr/lib/node_modules/gitprofiles/actions/list.js:8:25)
    at Command.list (/usr/lib/node_modules/gitprofiles/actions/list.js:18:5)
    at Command.listener (/usr/lib/node_modules/gitprofiles/node_modules/commander/index.js:360:8)
    at emitTwo (events.js:126:13)
    at Command.emit (events.js:214:7)
    at Command.parseArgs (/usr/lib/node_modules/gitprofiles/node_modules/commander/index.js:799:12)
    at Command.parse (/usr/lib/node_modules/gitprofiles/node_modules/commander/index.js:563:21)
    at bootstrap.then (/usr/lib/node_modules/gitprofiles/index.js:31:23)
    at <anonymous>
```

**Comment by brunooomelo** [comment]
Resolved #3
